/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchLabsRouteImport } from './routes/search_.labs'
import { Route as LabsTestsRouteImport } from './routes/labs_.tests'
import { Route as LabsSlotsRouteImport } from './routes/labs_.slots'
import { Route as LabsReviewsRouteImport } from './routes/labs_.reviews'
import { Route as SearchLabsLab_idRouteImport } from './routes/search_.labs_.$lab_id'
import { Route as LabsLab_idAppointmentsRouteImport } from './routes/labs_.$lab_id_.appointments'
import { Route as SearchLabsLab_idTestsTest_idRouteImport } from './routes/search_.labs_.$lab_id_.tests.$test_id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchLabsRoute = SearchLabsRouteImport.update({
  id: '/search_/labs',
  path: '/search/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsTestsRoute = LabsTestsRouteImport.update({
  id: '/labs_/tests',
  path: '/labs/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsSlotsRoute = LabsSlotsRouteImport.update({
  id: '/labs_/slots',
  path: '/labs/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsReviewsRoute = LabsReviewsRouteImport.update({
  id: '/labs_/reviews',
  path: '/labs/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchLabsLab_idRoute = SearchLabsLab_idRouteImport.update({
  id: '/search_/labs_/$lab_id',
  path: '/search/labs/$lab_id',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsLab_idAppointmentsRoute = LabsLab_idAppointmentsRouteImport.update({
  id: '/labs_/$lab_id_/appointments',
  path: '/labs/$lab_id/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchLabsLab_idTestsTest_idRoute =
  SearchLabsLab_idTestsTest_idRouteImport.update({
    id: '/search_/labs_/$lab_id_/tests/$test_id',
    path: '/search/labs/$lab_id/tests/$test_id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/labs': typeof LabsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/reviews': typeof ReviewsRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/labs/reviews': typeof LabsReviewsRoute
  '/labs/slots': typeof LabsSlotsRoute
  '/labs/tests': typeof LabsTestsRoute
  '/search/labs': typeof SearchLabsRoute
  '/labs/$lab_id/appointments': typeof LabsLab_idAppointmentsRoute
  '/search/labs/$lab_id': typeof SearchLabsLab_idRoute
  '/search/labs/$lab_id/tests/$test_id': typeof SearchLabsLab_idTestsTest_idRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/labs': typeof LabsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/reviews': typeof ReviewsRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/labs/reviews': typeof LabsReviewsRoute
  '/labs/slots': typeof LabsSlotsRoute
  '/labs/tests': typeof LabsTestsRoute
  '/search/labs': typeof SearchLabsRoute
  '/labs/$lab_id/appointments': typeof LabsLab_idAppointmentsRoute
  '/search/labs/$lab_id': typeof SearchLabsLab_idRoute
  '/search/labs/$lab_id/tests/$test_id': typeof SearchLabsLab_idTestsTest_idRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/labs': typeof LabsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/reviews': typeof ReviewsRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/labs_/reviews': typeof LabsReviewsRoute
  '/labs_/slots': typeof LabsSlotsRoute
  '/labs_/tests': typeof LabsTestsRoute
  '/search_/labs': typeof SearchLabsRoute
  '/labs_/$lab_id_/appointments': typeof LabsLab_idAppointmentsRoute
  '/search_/labs_/$lab_id': typeof SearchLabsLab_idRoute
  '/search_/labs_/$lab_id_/tests/$test_id': typeof SearchLabsLab_idTestsTest_idRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/labs'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/refund'
    | '/register'
    | '/reviews'
    | '/search'
    | '/terms'
    | '/labs/reviews'
    | '/labs/slots'
    | '/labs/tests'
    | '/search/labs'
    | '/labs/$lab_id/appointments'
    | '/search/labs/$lab_id'
    | '/search/labs/$lab_id/tests/$test_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/labs'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/refund'
    | '/register'
    | '/reviews'
    | '/search'
    | '/terms'
    | '/labs/reviews'
    | '/labs/slots'
    | '/labs/tests'
    | '/search/labs'
    | '/labs/$lab_id/appointments'
    | '/search/labs/$lab_id'
    | '/search/labs/$lab_id/tests/$test_id'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/labs'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/refund'
    | '/register'
    | '/reviews'
    | '/search'
    | '/terms'
    | '/labs_/reviews'
    | '/labs_/slots'
    | '/labs_/tests'
    | '/search_/labs'
    | '/labs_/$lab_id_/appointments'
    | '/search_/labs_/$lab_id'
    | '/search_/labs_/$lab_id_/tests/$test_id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  LabsRoute: typeof LabsRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RefundRoute: typeof RefundRoute
  RegisterRoute: typeof RegisterRoute
  ReviewsRoute: typeof ReviewsRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  LabsReviewsRoute: typeof LabsReviewsRoute
  LabsSlotsRoute: typeof LabsSlotsRoute
  LabsTestsRoute: typeof LabsTestsRoute
  SearchLabsRoute: typeof SearchLabsRoute
  LabsLab_idAppointmentsRoute: typeof LabsLab_idAppointmentsRoute
  SearchLabsLab_idRoute: typeof SearchLabsLab_idRoute
  SearchLabsLab_idTestsTest_idRoute: typeof SearchLabsLab_idTestsTest_idRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search_/labs': {
      id: '/search_/labs'
      path: '/search/labs'
      fullPath: '/search/labs'
      preLoaderRoute: typeof SearchLabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs_/tests': {
      id: '/labs_/tests'
      path: '/labs/tests'
      fullPath: '/labs/tests'
      preLoaderRoute: typeof LabsTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs_/slots': {
      id: '/labs_/slots'
      path: '/labs/slots'
      fullPath: '/labs/slots'
      preLoaderRoute: typeof LabsSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs_/reviews': {
      id: '/labs_/reviews'
      path: '/labs/reviews'
      fullPath: '/labs/reviews'
      preLoaderRoute: typeof LabsReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search_/labs_/$lab_id': {
      id: '/search_/labs_/$lab_id'
      path: '/search/labs/$lab_id'
      fullPath: '/search/labs/$lab_id'
      preLoaderRoute: typeof SearchLabsLab_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs_/$lab_id_/appointments': {
      id: '/labs_/$lab_id_/appointments'
      path: '/labs/$lab_id/appointments'
      fullPath: '/labs/$lab_id/appointments'
      preLoaderRoute: typeof LabsLab_idAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search_/labs_/$lab_id_/tests/$test_id': {
      id: '/search_/labs_/$lab_id_/tests/$test_id'
      path: '/search/labs/$lab_id/tests/$test_id'
      fullPath: '/search/labs/$lab_id/tests/$test_id'
      preLoaderRoute: typeof SearchLabsLab_idTestsTest_idRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  LabsRoute: LabsRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RefundRoute: RefundRoute,
  RegisterRoute: RegisterRoute,
  ReviewsRoute: ReviewsRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  LabsReviewsRoute: LabsReviewsRoute,
  LabsSlotsRoute: LabsSlotsRoute,
  LabsTestsRoute: LabsTestsRoute,
  SearchLabsRoute: SearchLabsRoute,
  LabsLab_idAppointmentsRoute: LabsLab_idAppointmentsRoute,
  SearchLabsLab_idRoute: SearchLabsLab_idRoute,
  SearchLabsLab_idTestsTest_idRoute: SearchLabsLab_idTestsTest_idRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
